services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  kafkaproducer:
#    build: .
#    container_name: kafkaproducer
#    depends_on:
#      - broker
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'
#
#  kafkaconsumer:
#    build: C:\Users\123\IdeaProjects\kafkaCons
#    container_name: kafkacons
#    depends_on:
#      - broker
#    ports:
#      - "8081:8081"
#    environment:
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'broker:29092'

